### ISSUE TITLE
Check for received shares

### ISSUE THREAD

**Issue by a3slade** [Trust-Machines/frost#12]
Each party needs to make sure that they received a share from everybody and only received one share per party (or only added it once in case they resend it).

**Comment by a3slade** [comment]
This was partially addressed by https://github.com/Trust-Machines/frost/issues/20
We still need to return which parties are missing. It's TBA if that should happen within this code or in the code that parses the broadcast msgs.

**Comment by xoloki** [comment]
Fixed in #54
