### ISSUE TITLE
Persist enough state to recover all data after a restart

### ISSUE THREAD

**Issue by a3slade** [Trust-Machines/frost#21]
Parties need two pieces of data in order to sign: their private nonces, and their share of the secret key.  There is no way to recreate the first, so store it directly.  The second can be reconstructed from the shares, but if we store them instead we use vastly more space and gain nothing in terms of the security.  So store the secret share directly as well.

Eventually we will want to use a HSM to hold keys, either a local encryption key or just shove everything in.  Getting the HSM to do the math we want will be non-trivial, so encrypting with an HSM stored key will likely be a much lower hanging fruit.

**Comment by xoloki** [comment]
We are using ephemeral nonces now, so only need to store secret share and (until DKG is complete) the poly.
