### ISSUE TITLE
Analyze `fn get_B_rho_R_vec`

### ISSUE THREAD

**Issue by xoloki** [Trust-Machines/frost#26]
This `fn` returns 3 values but we only ever use 2 of them.   However, all values are interrelated so maybe it's impossible to do anything other than calculate all 3 every time.  If that's the case, find a better name, since we don't actually return rho, and do return R.

**Comment by a3slade** [comment]
We call it twice and we use a different two of them such that all three are used somewhere:

let (_B, R_vec, R) = get_B_rho_R_vec(&signers, &self.B, self.nonce_ctr, &msg);
let (B, _R_vec, R) = get_B_rho_R_vec(&signers, &self.B, nonce_index, &msg);

The rho vector is used by the SA when it asserts that the individual z_i is correct.

At first I had three fns that each returned one (and both the Party and SA had to call all three bc of the relationship) but then I changed it to one fn. Both options feel meh.

I agree that it's an absolutely horrible name! I would prefer something like get_<word> where "word" is something that reflects the general purpose of all three.

**Comment by xoloki** [comment]
Renamed in PR #41 , so closing.
