### ISSUE TITLE
Create functions to serialize & deserialize info that needs to get shared

### ISSUE THREAD

**Issue by a3slade** [Trust-Machines/frost#29]
For key generation:

* Commitments to poly coefficients (including proof for the poly's constant).
    * Each party's commitments are available via get_poly_commitment() as a T-long vector of Points
        plus an "ID" (of two Scalars and a Point) that contains the proof.
        (Note: We can change one of those Scalars to a usize to save a little space).
    * They also need to include their index or PK or something so people know which party it came from
    * We should probably have them sign a hash of the whole vector + id to verify it came from them

    * All of these are sent back to each Party in compute_secret() and to the SignatureAggregate at it's creation
    * Right now, compute_secret() is taking a vector of everybody's commitments but I can change that to accept each party's commitment separately if that's easier w/ a bit of extra book-keeping, just let me know.

    The total sent here should be roughly N * ((T+1) * sizeof(Point) + (2*sizeof(Scalar)) + const)

* Shares of the secret
    * Each party needs to send every other party an encrypted share
       They either need to include their own share for themselves (encrypted with their own pk) for recovery purposes or they need to save that somewhere.
        These should use a PK for each party that is not related to their FROST key
        Right now these are coming from get_shares() as a HashMap but we can change that to a vector if that's easier?
        They are returning to each party in compute_secret() again as a HashMap but we can change that too
            - the reason this is currently a HashMap was because I thought that might be the easiest way to collect the shares from each of the parties. We need to make sure to re-request shares from any missing parties
    * I'm thinking this will look something like a vector of (index, Encrypted(Scalar))
        There needs to be some canonical order for the parties and the index here is that (or it could just have their PK or whatever)
        But they could also just be packed in order w/o the index
    * Again, they should probably sign this but they can sign them all together or something

    The total sent here should be roughly N * (N * sizeof(Encrypted(Scalar)) +  const)

--------------------------------------------------

For nonce generation:
    * We can be flexible on the number of nonces sent in a batch.
    * Each party needs to send 2 Points per num_nonces.
    * gen_nonces() will create a batch.
    * These nonces get sent back to the party (as a vector of all the party's nonces) in set_group_nonces() and to the SignatureAggregator at its creation
        These should be in a vector that is sorted according to the canonical ordering of the parties  

    The total sent here should be roughly N * num_nonces * 2 * sizeof(Point) + (N * const)

--------------------------------------------------

For signing:
    * The msg, list of signers, & nonce_ctr needs to be sent to everyone
        This should be Len(msg) + (T+1) * sizeof(usize)

    * Each party returns a signature that has a scalar & a point

**Comment by netrome** [comment]
I have a PR now that adds serialization support to central types, and attempts to measure the bandwidth usage in the benchmarking script: https://github.com/Trust-Machines/frost/pull/34

> Right now these are coming from get_shares() as a HashMap but we can change that to a vector if that's easier?
From a serialization perspective, this should not matter. The representations of a HashMap or a tuple Vector should be equivalent (at least in size) in most serialization formats. And in terms of ergonomics, serde makes it super easy to serialize arbitrarily complex data structures.

**Comment by xoloki** [comment]
Once PR #41 is merged, re-evaluate this to see what work is remaining.  At least the share encryption will still be required.

**Comment by xoloki** [comment]
@netrome PR #41 has been merged, is there any else you want for this issue or can I close it?

**Comment by netrome** [comment]
> @netrome PR #41 has been merged, is there any else you want for this issue or can I close it?

Great, there's nothing more I want to push for at the moment so let's close this one.
