### ISSUE TITLE
Figure out how someone can *prove* if someone else gave them a bad share

### ISSUE THREAD

**Issue by a3slade** [Trust-Machines/frost#50]
Let's call mallory's polynomial evaluated at Alice's index f_m(a).
Everyone, including Alice, can calculate f_m(a)*G.

Only Alice gets f_m(a) by itself. Mallory encrypts this to her.

Suppose that Mallory sends Alice a bad share. Let's call this share blah.
Alice can see that blah * G != f_m(a)*G.

How does Alice prove this to everyone else?

She needs to prove that 1) the received share is bad and 2) that this was the share that Mallory actually sent her and she's not just making a false accusation.

**Comment by xoloki** [comment]
Once we have pubkeys for all parties, this should be trivial.

All shares are signed and encrypted.  If Alice gets a bad share, she reveals it, along with her private key.  Everyone can decrypt the share, and verify that it is bad and comes from Mallory.

Alice then generates a new key, and registers it with the sbtc contract.

The extra signatures will be costly in terms of bandwidth, but we need them anyway.
